FROM alpine:latest
#ENTRYPOINT es el comando que se ejecuta cuando se inicia el container - solo se permite uno por Dockerfile
#Si en el Dockerfile no se especifica ningun CMD, se ejecuta el CMD de la imagen base
#Si en el Dockerfile se especifica un CMD, se ejecuta el CMD de la imagen base y luego el CMD del Dockerfile
#Si en el Dockerfile se especifica un ENTRYPOINT, se ejecuta el ENTRYPOINT de la imagen base y luego el CMD del Dockerfile
ENTRYPOINT ["echo","Hola mundo con ENTRYPOINT"]