FROM python:3.9-slim

#directorio de trabajo dentro del contenedor
WORKDIR /app
#copia el archivo saludo.py al contenedor
COPY saludo.py .

#ejecuta el archivo saludo.py al iniciar el contenedor
CMD ["python", "saludo.py"]
